### ISSUE TITLE
Installation of non-recent GHC fails on MacOS

### ISSUE THREAD

**Issue by larskuhtz** [actions/setup-haskell#21]
The following actions with `matrix.ghc == '8.8.3'`

```yaml
    - name: Install GHC and Cabal
      uses: actions/setup-haskell@v1.1.0
      with:
         ghc-version: ${{ matrix.ghc }}
         cabal-version: ${{ matrix.cabal }}
    - name: Confirm GHC and Cabal installation
      run: |
        ghc --version
        cabal --version
```

yields this result on MacOS:

<img width="596" alt="image" src="https://user-images.githubusercontent.com/1369810/83801257-af36e080-a65d-11ea-865b-dccbd0bc6513.png">

Requested version GHC version: 8.8.3
Actually available GHC version: 8.10.1

Here is the link to the original workflow run: https://github.com/kadena-io/chainweb-node/runs/739791712?check_suite_focus=true
