### ISSUE TITLE
cabal update fails

### ISSUE THREAD

**Issue by jhidding** [actions/setup-haskell#4]
Using the template exactly as it is given,

```yaml
name: Haskell CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.6.5'
        cabal-version: '3.0'
    - name: Install dependencies
      run: |
        cabal update
        cabal install --only-dependencies --enable-tests
    - name: Build
      run: |
        cabal configure --enable-tests
        cabal build
    - name: Run tests
      run: cabal test
```

I get the following error

```
Run cabal update
Config file path source is default config file.
Config file /home/runner/.cabal/config not found.
Writing default configuration to /home/runner/.cabal/config
Downloading the latest package list from hackage.haskell.org
cabal: --enable-tests was specified, but tests can't be enabled in a remote
package

##[error]Process completed with exit code 1.
```
