### ISSUE TITLE
Setting GHC/Cabal versions doesn't work with macOS

### ISSUE THREAD

**Issue by johnjcamilleri** [actions/setup-haskell#43]
Take this workflow file:

```yaml
name: Main
on: push
jobs:
  main:
    runs-on: macos-latest
    steps:
    - uses: actions/setup-haskell@v1.1
      with:
        ghc-version: 8.6.5
        cabal-version: 2.4
    - run: ghc --version
    - run: cabal --version
```

The output I get when running the action is:

```
Run actions/setup-haskell@v1.1
Preparing to setup a Haskell environment
Resolved 2.4 to 2.4.1.0
Installing ghc version 8.6.5
Installing cabal version 2.4.1.0
Setting up cabal
```
```
Run ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.10.2
```
```
Run cabal --version
cabal-install version 3.2.0.0
compiled using version 3.2.0.0 of the Cabal library 
```

When I try replacing `macos-latest` with `ubuntu-latest`, I get the output I expect:
```
Run ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.6.5
```
```
Run cabal --version
cabal-install version 2.4.1.0
compiled using version 2.4.1.0 of the Cabal library 
```

You can see my MWE in action [here](https://github.com/johnjcamilleri/test-action-setup-haskell/actions).
