### ISSUE TITLE
Provide `hlint` executable.

### ISSUE THREAD

**Issue by patrickt** [actions/setup-haskell#5]
This would be really nice to have by default.

**Comment by LeifW** [comment]
Is there a way to add hlint yourself, even if it's not added by this action?

**Comment by patrickt** [comment]
@LeifW You can always `cabal install` and cache it (as [here](https://github.com/github/semantic/blob/master/.github/workflows/haskell.yml#L56)), or you can run `wget` to download a Linux binary from the [releases page](https://github.com/ndmitchell/hlint/releases).

**Comment by Twonki** [comment]
I think having hlint is not what most people expect from a setup-haskell action. 

Other people would be missing other libraries too then, such as quickcheck or hunit or something other essential. 

However, I think whats maybe a good idea is to have a list of packages to be installed with the github action? 

```
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.8.3'
        cabal-version: '3.2'
        packages: 
            - quickcheck
            - hlint
```

What do you think @patrickt & @LeifW ?
